apiVersion: apps/v1
kind: {{ if not .Values.autoscaling.enabled }}StatefulSet{{- else }}Deployment{{- end }}
metadata:
  name: {{ include "appsmith.fullname" . }}
  namespace: {{ include "appsmith.namespace" . }}
  labels:
    {{- include "appsmith.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  serviceName: {{ include "appsmith.fullname" . }}
  updateStrategy:
  {{- else }}
  strategy:
  {{- end }}
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "appsmith.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "appsmith.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      serviceAccountName: {{ template "appsmith.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.redis.enabled }}
      - name: redis-init-container
      {{- if ((.Values.initContainer.redis).image) }}
        image: {{ .Values.initContainer.redis.image }}
      {{- else }}
        image: "docker.io/library/redis:6.2-alpine"
      {{- end }}
        command: ['sh', '-c', "until redis-cli -h {{ include "appsmith.fullname" . }}-redis-master.{{.Release.Namespace}}.svc.cluster.local ping ; do echo waiting for redis; sleep 2; done"]
      {{- end }}
      {{- if .Values.mongodb.enabled }}
      - name: mongo-init-container
      {{- if ((.Values.initContainer.mongodb).image) }}
        image: {{ .Values.initContainer.mongodb.image }}
      {{- else }}
        image:  "docker.io/bitnami/mongodb:5.0.17-debian-11-r5"
      {{- end }}
        command: ['sh', '-c', "until mongo --host appsmith-mongodb.{{.Release.Namespace}}.svc.cluster.local --eval 'db.runCommand({ping:1})' ; do echo waiting for mongo; sleep 2; done"]
      {{- end }}
      {{- if .Values.postgresql.enabled }}
      - name: psql-init-container
        image: alpine:latest
        command: ['sh', '-c', "apk add postgresql-client; until pg_isready -h {{ include "appsmith.fullname" . }}-postgresql.{{.Release.Namespace}}.svc.cluster.local; do echo waiting for postgresql; sleep 2; done"]
      {{- end }}
      containers:
        - name: {{ .Values.containerName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "index.docker.io/appsmith/appsmith-ee:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: supervisord
              containerPort: 9001
              protocol: TCP
          {{- $probes := .Values.probes | default dict }}
          startupProbe:
            # The `livenessProbe` and `readinessProbe` will be disabled until the `startupProbe` is successful.
            httpGet:
              port: http
              path: {{ dig "startupProbe" "api" "/api/v1/health" $probes }}
            failureThreshold: {{ dig "startupProbe" "failureThreshold" 3 $probes }}
            periodSeconds: {{ dig "startupProbe" "periodSeconds" 60 $probes }}
          livenessProbe:
            httpGet:
              port: http
              path: {{ dig "livenessProbe" "api" "/api/v1/health" $probes }}
            failureThreshold: {{ dig "livenessProbe" "failureThreshold" 3 $probes }}
            periodSeconds: {{ dig "livenessProbe" "periodSeconds" 60 $probes }}
          readinessProbe:
            httpGet:
              port: http
              path: {{ dig "readinessProbe" "api" "/api/v1/health" $probes }}
            failureThreshold: {{ dig "readinessProbe" "failureThreshold" 3 $probes }}
            periodSeconds: {{ dig "readinessProbe" "periodSeconds" 60 $probes }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /appsmith-stacks
          envFrom:
            - configMapRef:
                name: {{ include "appsmith.fullname" . }}
            {{- if .Values.secretName }}
            - secretRef:
                name: {{ .Values.secretName }}
            {{- end }}
      {{- if .Values.image.pullSecrets}}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- end }}
      volumes:
  {{- if not .Values.persistence.enabled }}
      - name: data
        emptyDir: {}
  {{- else if and (not .Values.autoscaling.enabled) (.Values.persistence.enabled) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- if .Values.persistence.annotations}}
        annotations:
          {{- include "tplvalues.render" (dict "value" .Values.persistence.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.volumeClaimTemplates.selector }}
        selector:
          {{- include "tplvalues.render" (dict "value" .Values.persistence.volumeClaimTemplates.selector "context" $) | nindent 10 }}
        {{- end }}
        {{ include "storage.class" (dict "persistence" .Values.persistence "global" .Values.global) | nindent 8 }}
  {{- else }}
      - name: data
        persistentVolumeClaim:
          {{- if .Values.persistence.existingClaim.enabled }}
          claimName: {{ .Values.persistence.existingClaim.claimName }}
          {{- else }}
          claimName: {{ include "appsmith.fullname" . }}
          {{- end }}
  {{- end }}
