name: Cyclic Dependency Check

on:
  pull_request:
    paths:
      - "app/client/src/**"

jobs:
  check-cyclic-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/client
        shell: bash

    steps:
      # The checkout steps MUST happen first because the default directory is set according to the code base.
      # GitHub Action expects all future commands to be executed in the code directory. Hence, we need to check out
      # the code before doing anything else.

      # Check out merge commit with the base branch in case this workflow is invoked via pull request
      - name: Checkout the merged commit from PR and base branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: app/client/package.json

      # actions/setup-node@v3 doesn’t work properly with Yarn 3
      # when the project lives in a subdirectory: https://github.com/actions/setup-node/issues/488
      # Restoring the cache manually instead
      - name: Restore Yarn cache
        uses: actions/cache@v3
        with:
          path: app/client/.yarn/cache
          key: v1-yarn3-${{ hashFiles('app/client/yarn.lock') }}
          restore-keys: |
            v1-yarn3-

      # Install all the dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Check for cyclic dependencies and save the output
      - name: Check for Cyclic Dependencies
        id: cyclic-check
        run: |
          OUTPUT=$(yarn check-cyclic-deps 2>&1) || echo "{cyclic_deps}={OUTPUT}" >> $GITHUB_OUTPUT

      # Comment on the PR if cyclic dependencies are found
      - name: Comment the result on PR
        if: steps.cyclic-check.outputs.cyclic_deps
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const output = `${{ steps.cyclic-check.outputs.cyclic_deps }}`;
            const message = `🔄 Cyclic Dependency Check:\n\`\`\`\n${output}\n\`\`\``;
            github.issues.createComment({
              ...context.repo,
              issue_number: ${{ github.event.pull_request.number }},
              body: message
            });

      # Saving the cache to use it in subsequent runs
      - name: Save Yarn cache
        uses: actions/cache/save@v3
        with:
          path: app/client/.yarn/cache
          key: v1-yarn3-${{ hashFiles('app/client/yarn.lock') }}
          restore-keys: |
            v1-yarn3-
