name: PR Automation test suite with N count

on:
  pull_request:
    branches:
      - release
      - pg
    types:
      - labeled
  workflow_dispatch:
    inputs:
      count:
        description: 'Number of times to run the pipeline'
        required: true
        default: '1'
        type: integer
      count_to_run:
        description: 'Comma-separated list of matrix values'
        required: true
        default: '0,1,2,3,4,5,6,7,8,9,10'
        type: string

jobs:
  parse-tags:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ok-to-test'
    permissions:
      pull-requests: write
    steps:

      # Checkout the code in the current branch in case the workflow is called because of a branch push event
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v4
        with:
            repository: appsmithorg/appsmith

      # Reads the PR description to retrieve the /ok-to-test or, if that's absent, the /test command
      - name: Read tags from PR description
        uses: actions/github-script@v7
        id: parseTags
        env:
          NODE_PATH: "${{ github.workspace }}/.github/workflows/scripts"
        with:
          script: |
            require("test-tag-parser.js")({core, context, github})

      # Check if @tag.All is present in tags and set matrix values
      - name: Check if @tag.All is present in tags
        id: checkAll
        run: |
          if [[ -n "${{ steps.parseTags.outputs.spec }}" ]]; then
            echo "count_to_run=0" >> $GITHUB_ENV
          else
            tags="${{ steps.parseTags.outputs.tags }}"
            if [[ $tags == "@tag.All" ]]; then
              echo "count_to_run=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59" >> $GITHUB_ENV
            else
              echo "count_to_run=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19" >> $GITHUB_ENV
            fi
          fi

      # Update the PR with run details
      - name: Add test response with link to workflow run
        uses: actions/github-script@v7
        env:
          NODE_PATH: "${{ github.workspace }}/.github/workflows/scripts"
          BODY: |
            Your tests are running.
            Tests running at: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>
            Commit: ${{ github.event.pull_request.head.sha }}
            Workflow: `${{ github.workflow }}`
            Tags: `${{ steps.parseTags.outputs.tags }}`
            Spec: `${{ steps.parseTags.outputs.spec }}`
        with:
          script: |
            require("write-cypress-status.js")({core, context, github}, "important", process.env.BODY)

  # Call the workflow to run Cypress tests with matrix values
  perform-test:
    needs: [parse-tags]
    if: success()
    strategy:
      matrix:
        count_to_run: ${{ fromJson('[' + github.event.inputs.count_to_run + ']') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the head commit of the branch
        uses: actions/checkout@v4
        with:
            repository: appsmithorg/appsmith

      - name: Run Cypress tests
        uses: ./.github/workflows/pr-cypress.yml
        secrets: inherit
        with:
          tags: ${{ needs.parse-tags.outputs.tags }}
          spec: ${{ needs.parse-tags.outputs.spec }}
          matrix: ${{ matrix.count_to_run }}
          is-pg-build: ${{ github.event.pull_request.base.ref == 'pg' }}