name: Vulnerability Scans

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '9 1 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKER_HUB_ORGANIZATION }}/appsmith-${{ vars.EDITION }}:release'
          format: json
          severity: CRITICAL,HIGH
          scanners: vuln
          timeout: 15m
          output: output.json

      - name: Full JSON output
        run: cat output.json

      - name: Report
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require("fs/promises")
            const results = JSON.parse(await fs.readFile("output.json")).Results

            const headers = [
              "CVE",
              "Severity",
              "Path",
              "Update to fix",
            ].map(data => ({ data, header: true }))

            const rows = [headers]
            const counts = {}

            for (const result of results) {
              if (result.Vulnerabilities == null) {
                continue
              }
              for (const vuln of result.Vulnerabilities) {
                rows.push([
                  vuln.VulnerabilityID,
                  vuln.Severity,
                  vuln.PkgPath,
                  vuln.InstalledVersion + " &rarr; " + (vuln.FixedVersion || "N/A"),
                ])
                counts[vuln.Severity] = (counts[vuln.Severity] || 0) + 1
              }
            }

            await core.summary
              .addHeading("Scan Results")
              .addCodeBlock(JSON.stringify(counts, null, 4), "json")
              .addTable(rows)
              .write()
